name: Greetings

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: 'Thats an Upsi. Thanks'' first issue'
        pr-message: 'Welcome to the Connect_4_Network Maddnes'' first pr'
